"""Read a Ramabana session log and give a score to the tool calls in it.

Docs: https://Karthik777.github.io/drona/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['RAMABANA_HISTORY', 'DONE', 'RESEARCH_TOOLS', 'PROTOCOL', 'report', 'match_session', 'read_history', 'Finding',
           'Assessment', 'assess_turn', 'assess_history', 'main']

# %% ../nbs/00_core.ipynb #1ec3b1b4
from dataclasses import dataclass, asdict
from pathlib import Path
import json, sys

from fastcore.script import call_parse

# %% ../nbs/00_core.ipynb #cc9e6266
RAMABANA_HISTORY = Path.home()/'.config/ramabana/agent-history.jsonl'
DONE = ('complete',)

def _row(line):
    try: return json.loads(line) if line.strip() else None
    except json.JSONDecodeError: return None

def report(fn, *args, **kw):
    "Run `fn`. Show an expected failure as a message, not as a traceback."
    try: return fn(*args, **kw)
    except (ValueError, FileNotFoundError) as e:
        print(e, file=sys.stderr)
        sys.exit(2)

def match_session(
    turns,   # turns from `read_history`
    session, # session id, id prefix, or `latest`
):
    "The turns of one session. An exact id has precedence over a prefix."
    ids = [s for t in turns if (s := t.get('session'))]
    if not ids: raise ValueError('no turn carries a session id')
    if session == 'latest': session = ids[-1]
    hits = ([t for t in turns if t.get('session') == session]
            or [t for t in turns if str(t.get('session') or '').startswith(session)])
    if not hits: raise ValueError(f'no session matches {session!r}')
    if len({t.get('session') for t in hits}) > 1: raise ValueError(f'session {session!r} is ambiguous')
    return hits

def read_history(
    path=RAMABANA_HISTORY, # Ramabana `agent-history.jsonl` path
    session=None,          # session id, id prefix, or `latest`; every session when omitted
    states=DONE,           # turn states to keep; `None` keeps every state
):
    "The Ramabana turns, in the sequence that Ramabana wrote them."
    p = Path(path).expanduser()
    if not p.exists(): raise FileNotFoundError(f'no Ramabana history at {p}')
    rows = [t for line in p.read_text().splitlines() if isinstance(t := _row(line), dict)]
    if not rows: raise ValueError(f'{p} has no turns')
    turns = rows if states is None else [t for t in rows if t.get('state', 'complete') in states]
    if not turns:
        raise ValueError(f'no turn in {p.name} has the state {" or ".join(states)}; use --every-state to keep the others')
    return match_session(turns, session) if session else turns

# %% ../nbs/00_core.ipynb #47e89b6e
@dataclass(frozen=True)
class Finding:
    "One fault in the tool calls of a turn."
    kind: str
    tool: str
    index: int
    message: str

@dataclass(frozen=True)
class Assessment:
    "The score and the findings for one turn or more."
    score: int
    calls: int
    findings: tuple[Finding, ...]

    def dict(self):
        "The assessment as data for JSON."
        return {'score': self.score, 'calls': self.calls, 'findings': [asdict(f) for f in self.findings]}

def _score(findings): return max(0, 100 - 20*len(findings))

# %% ../nbs/00_core.ipynb #c187f10c
RESEARCH_TOOLS = {'web_search', 'read_url', 'search_code', 'run_shell'}
PROTOCOL = (
    ('edit_cell', ('could not parse commands',),
     'Use the notebook editor command format from its current tool contract.'),
    ('run_shell', ('usage:', 'unrecognized arguments'),
     'Read the project command contract before retrying.'),
)

def _args_text(action): return ' '.join(str(v) for v in (action.get('args') or {}).values())

def _reads_repo(action):
    return action.get('tool') == 'run_shell' and 'fossick read-gh-repo' in _args_text(action)

def assess_turn(turn):
    "Give a score to the tool calls of one Ramabana turn."
    acts, findings = turn.get('activity') or [], []
    prompt = str(turn.get('prompt') or '').lower()
    if 'github' in prompt and 'fossick' in prompt:
        research = [(i, a) for i, a in enumerate(acts) if a.get('tool') in RESEARCH_TOOLS]
        if research and not _reads_repo(research[0][1]):
            i, a = research[0]
            findings.append(Finding('route', a.get('tool', ''), i,
                                    'Use fossick read-gh-repo as the first repository research call.'))
    seen = set()
    for i, a in enumerate(acts):
        if a.get('ok', True): continue
        tool, detail = a.get('tool', ''), str(a.get('detail') or '').lower()
        key = (tool, json.dumps(a.get('args') or {}, sort_keys=True, default=str))
        if key in seen:
            findings.append(Finding('repeat_failure', tool, i,
                                    'Diagnose or change route before repeating a failed call.'))
        seen.add(key)
        for name, needles, message in PROTOCOL:
            if tool == name and any(n in detail for n in needles):
                findings.append(Finding('tool_protocol', tool, i, message))
                break
    return Assessment(_score(findings), len(acts), tuple(findings))

def assess_history(turns):
    "Give one score to a group of turns."
    each = [assess_turn(t) for t in turns]
    findings = tuple(f for a in each for f in a.findings)
    return Assessment(_score(findings), sum(a.calls for a in each), findings)

# %% ../nbs/00_core.ipynb #eb15d7c9
@call_parse
def main(
    history: str=str(RAMABANA_HISTORY), # Ramabana history path
    session: str=None,                  # session id, id prefix, or `latest`
    every_state: bool=False,            # score abandoned and failed turns too
):
    "Give a score to the tool calls in a Ramabana log."
    turns = report(read_history, history, session, states=None if every_state else DONE)
    print(json.dumps(assess_history(turns).dict(), indent=2))
