"""Assess Ramabana tool routes and build a Urai warm-start history.

Docs: https://Karthik777.github.io/drona/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['RAMABANA_HISTORY', 'SHELL_TOOLS', 'ROUND_REVISION', 'Finding', 'Assessment', 'read_history', 'tool_args',
           'bypass_tool', 'assess_turn', 'assess_history', 'warm_start', 'drona_version', 'receipt_path',
           'register_completion', 'completion_valid', 'prepare_chat', 'main']

# %% ../nbs/00_core.ipynb #d04693b6
from dataclasses import dataclass, asdict
import json, re, time, uuid
from fastcore.xtras import Path
from fastcore.script import call_parse
from fastcore.xdg import xdg_state_home
from fastcore.foundation import L
from urai import ToolCall, mk_tool_res_msg
from . import __version__

# %% ../nbs/00_core.ipynb #2edea58c
@dataclass(frozen=True)
class Finding:
    "One tool-route problem in a recorded turn."
    kind: str
    tool: str
    index: int
    message: str

@dataclass(frozen=True)
class Assessment:
    "The route score and findings for one or more turns."
    score: int
    calls: int
    findings: tuple[Finding, ...]

# %% ../nbs/00_core.ipynb #8e5631ea
RAMABANA_HISTORY = Path.home()/'.config/ramabana/agent-history.jsonl'

def _loads(s):
    try: return json.loads(s)
    except (json.JSONDecodeError, TypeError): return None

def read_history(
    path=RAMABANA_HISTORY, # Ramabana `agent-history.jsonl` path
    session=None,         # optional session id
):
    "Read completed Ramabana turns in append order, skipping partial lines."
    r = L(Path(path).expanduser().readlines()).map(_loads).filter(lambda x: isinstance(x, dict))
    return r if not session else r.filter(lambda x: x.get('session')==session)

def tool_args(action):
    "The call arguments of `action` as a dict."
    a = action.get('args')
    if isinstance(a, str): a = _loads(a)
    return a if isinstance(a, dict) else {}

# %% ../nbs/00_core.ipynb #cf182995
_RESEARCH_TOOLS = {'web_search', 'read_url', 'search_code', 'run_shell'}
_SCHEMA_ERRS = ('could not parse commands', 'JSONDecodeError', 'JSON decoder')
SHELL_TOOLS = (
    (r'git\s+status\b', 'git_status'), (r'git\s+diff\b', 'git_diff'), (r'git\s+(log|show)\b', 'git_log'),
    (r'git\s+commit\b', 'git_commit'), (r'git\s+(checkout|switch)\b', 'git_checkout'), (r'git\s+stash\b', 'git_stash'),
    (r'git\s+(push|pull|fetch)\b', 'git_remote'), (r'(rg|grep|ag)\b', 'grep'), (r'(find|fd)\b', 'ls'), (r'(ls|tree)\b', 'ls'),
    (r'(sed|perl)\s+-p?i\b', 'replace_text'), (r'(cat\s*>|tee\b)', 'create_file'), (r'sed\s+-n\b|(cat|head|tail|nl)\b', 'view_file'),
    (r'(curl|wget)\b', 'read_url'))
_PREFIX = re.compile(r'^(env(\s+-u\s+\S+|\s+\w+=\S+)*\s+|(\w+=\S+\s+)+)')
_GIT_OPTS = re.compile(r'^git\s+((-[Cc]\s+\S+|--\S+)\s+)+')

def _segments(command):
    for s in re.split(r'&&|;|\|\|', command):
        s = _GIT_OPTS.sub('git ', _PREFIX.sub('', s.strip()))
        if s and not s.startswith('cd '): yield s.split('|')[0].strip()

def bypass_tool(command, offered=None):
    "The dedicated tool `command` stands in for, if any."
    if not command: return None
    if re.search(r'&\s*$', command.strip()) and not command.strip().endswith('&&'): hit = 'run_shell_bg'
    else: hit = next((t for s in _segments(command) for rx,t in SHELL_TOOLS if re.match(rx, s)), None)
    return hit if hit and (offered is None or hit in offered) else None

def _is_fossick_repo(action):
    text = ' '.join(str(v) for v in tool_args(action).values())
    return action.get('tool') == 'run_shell' and 'fossick read-gh-repo' in text

def _first_research_finding(prompt, activities):
    if 'github' not in prompt.lower() or 'fossick' not in prompt.lower(): return None
    research = ((i, action) for i, action in enumerate(activities) if action.get('tool') in _RESEARCH_TOOLS)
    index, action = next(research, (None, None))
    if action is None or _is_fossick_repo(action): return None
    return Finding('route', action.get('tool', ''), index, 'Use fossick read-gh-repo as the first repository research call.')

def _failure_key(action): return (action.get('tool', ''), json.dumps(tool_args(action), sort_keys=True, default=str))

def _failure_findings(index, action, failed):
    if action.get('ok', False): return ()
    tool, detail, findings = action.get('tool', ''), str(action.get('detail', '')), []
    key = _failure_key(action)
    if key in failed: findings.append(Finding('repeat_failure', tool, index, 'Diagnose or change route before repeating a failed call.'))
    failed.add(key)
    if any(s in detail for s in _SCHEMA_ERRS):
        findings.append(Finding('schema', tool, index, 'Send arguments that match the tool schema exactly.'))
    if tool == 'run_shell' and ('usage:' in detail or 'unrecognized arguments' in detail):
        findings.append(Finding('tool_protocol', tool, index, 'Read the project command contract before retrying.'))
    return tuple(findings)

def assess_turn(turn):
    "Assess the tool route recorded in one Ramabana turn."
    activities, findings, failed = turn.get('activity') or [], [], set()
    route_finding = _first_research_finding(turn.get('prompt', ''), activities)
    if route_finding: findings.append(route_finding)
    for ind, a in enumerate(activities):
        if a.get('tool') == 'run_shell' and (t := bypass_tool(str(tool_args(a).get('command', '')))):
            findings.append(Finding('bypass', 'run_shell', ind, f'Use {t} instead of run_shell for this.'))
        findings.extend(_failure_findings(ind, a, failed))
    return Assessment(max(0, 100 - 20*len(findings)), len(activities), tuple(findings))

def assess_history(turns):
    "Assess several turns as one route corpus."
    assessments = [assess_turn(t) for t in turns]
    findings = tuple(f for a in assessments for f in a.findings)
    return Assessment(max(0, 100 - 20*len(findings)), sum(a.calls for a in assessments), findings)

# %% ../nbs/00_core.ipynb #2d9bf58b
ROUND_REVISION = 1

def warm_start():
    "Return a reviewed tool-routing demonstration as canonical Urai history."
    tc = ToolCall('run_shell', {
        'command': "fossick read-gh-repo https://github.com/AnswerDotAI/llmdojo --globs 'README*,llmdojo/*.py,pyproject.toml' --limit 30",
        'cwd': '.', 'timeout': 120})
    return [
        {'role': 'user', 'content': 'Use FOSSICK to research the AnswerDotAI llmdojo GitHub repository.'},
        {'role': 'assistant', 'content': 'The request names a GitHub repository and FOSSICK, so use its repository reader first.', 'tool_calls': [tc]},
        mk_tool_res_msg(tc, '# llmdojo\nLLM coding agents imitate what their context shows.'),
        {'role': 'assistant', 'content': 'FOSSICK read the repository directly. I will use its source files as the evidence.'},
    ]

def drona_version():
    "The warm-start revision."
    return f'{__version__}:{ROUND_REVISION}'

def receipt_path(state=None):
    "The completion receipt file."
    return Path(state) if state else xdg_state_home()/'drona/completions.json'

def register_completion(state=None):
    "Record one clean round and return its completion id."
    path, cid = receipt_path(state), uuid.uuid4().hex
    records = path.read_json() if path.exists() else {}
    records[cid] = {'version': drona_version(), 'at': time.time()}
    path.write_json(records, indent=2)
    return cid

def completion_valid(cid, state=None):
    "Does `cid` name a completion for the current round?"
    path = receipt_path(state)
    if not cid or not path.exists(): return False
    return (path.read_json().get(cid) or {}).get('version') == drona_version()

def prepare_chat(chat):
    "Prepend the Drona warm start to an empty Urai-compatible chat."
    if chat.hist: raise ValueError('Drona prepares an empty chat only')
    chat.hist = chat.fmt2hist(warm_start())
    if hasattr(chat, '_recreate_conv'): chat._recreate_conv()
    return chat

# %% ../nbs/00_core.ipynb #f4e8294d
@call_parse
def main(
    history: str=str(RAMABANA_HISTORY), # Ramabana history path
    session: str=None,                  # optional session id
):
    "Assess persisted Ramabana tool routes."
    a = assess_history(read_history(history, session))
    print(json.dumps({'score': a.score, 'calls': a.calls, 'findings': [asdict(f) for f in a.findings]}, indent=2))
