"""Capture, review, accept, and start curated tool-use rounds.

Docs: https://Karthik777.github.io/drona/rounds.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_rounds.ipynb.

# %% auto #0
__all__ = ['REVIEW_KEY', 'read_dialog', 'clean_dialog', 'latest_session', 'capture', 'compiled_history', 'accept',
           'bootstrap_prompt', 'start_commands', 'start_round', 'capture_cli', 'accept_cli', 'start_cli']

# %% ../nbs/01_rounds.ipynb #af82ef79
from dataclasses import asdict
from fastcore.xtras import Path
import json, shlex, subprocess
from aidialog.dialog import Dialog, snote, sprompt
from aidialog.hist import chat2dlg, dlg2chat
from aidialog.ipynb import read_ipynb, write_ipynb
from aidialog.msg_parts import Msg, Text, ToolUse, ToolResult
from fastcore.script import call_parse
from .core import RAMABANA_HISTORY, ROUNDS_DIR, assess_history, drona_version, read_history

# %% ../nbs/01_rounds.ipynb #d4f6b8c0
REVIEW_KEY = 'drona'

def read_dialog(source):
    "Read a Drona dialog notebook."
    if not (dlg := read_ipynb(source)): raise ValueError(f'Could not read dialog {source}')
    return dlg

def _prompts(dlg): return [m for m in dlg if m.msg_type == sprompt and not m.skipped]

def clean_dialog(source):
    "Prompt messages from a Drona notebook, without review notes."
    dlg = read_dialog(source)
    if not (prompts := _prompts(dlg)): raise ValueError('Dialog contains no prompt turns')
    return Dialog(prompts, name=dlg.name, meta=dlg.meta)

def _add_review(dlg, report, text):
    dlg.meta[REVIEW_KEY] = report
    dlg.mk_message(f'# Drona review\n\n{text}', idx=0, msg_type=snote, skipped=1, meta={REVIEW_KEY: report})

def _write_dlg(dlg, output):
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    write_ipynb(dlg, output)
    return output

# %% ../nbs/01_rounds.ipynb #252210fa
def latest_session(turns):
    "The newest session id in `turns`."
    return turns[-1].get('session') if turns else None

def _turn_msgs(turn, ti=0):
    "One Ramabana archive turn as typed Aidialog messages; `ti` keeps fallback call ids unique across turns."
    user = Msg('user', [Text(turn.get('prompt', ''))])
    replies = []
    for i, action in enumerate(turn.get('activity') or []):
        call_id = action.get('action_id') or action.get('id') or f'call_{ti}_{i}'
        tool = action.get('tool', '')
        args = action.get('args') or {}
        replies += [
            Msg('assistant', [ToolUse(id=call_id, name=tool, arguments=args)]),
            Msg('tool', [ToolResult(id=call_id, name=tool, arguments=args, text=str(action.get('detail', '')))]),
        ]
    if text := turn.get('reply', ''): replies.append(Msg('assistant', [Text(text)]))
    return [user, *replies]

def capture(
    output,                 # review notebook path
    session='latest',       # Ramabana session id, prefix, or `latest`
    history=RAMABANA_HISTORY, # Ramabana history path
    name=None,              # round name; output stem when omitted
):
    "Capture one persisted Ramabana session as a review notebook."
    turns = read_history(history)
    if not turns: raise ValueError('Ramabana history has no completed turns')
    if session == 'latest': session = latest_session(turns)
    matches = [t for t in turns if str(t.get('session', '')).startswith(session)]
    ids = {t.get('session') for t in matches}
    if not matches: raise ValueError(f'No Ramabana session matches {session!r}')
    if len(ids) > 1: raise ValueError(f'Ramabana session prefix {session!r} is ambiguous')
    assessment = assess_history(matches)
    msgs = [m for ti, turn in enumerate(matches) for m in _turn_msgs(turn, ti)]
    dlg = chat2dlg(msgs, name or Path(output).stem, mx=None)
    report = {'version': drona_version(), 'session': matches[0].get('session'), 'model': matches[-1].get('model'),
              'status': 'review', 'score': assessment.score,
              'findings': [asdict(f) for f in assessment.findings]}
    _add_review(dlg, report, 'Edit this dialog in Leela. Remove poor routes and sensitive content. Set `reviewer` when accepting.')
    return _write_dlg(dlg, output)

# %% ../nbs/01_rounds.ipynb #c2ca7765
def compiled_history(source):
    "Canonical Aidialog history from an accepted round."
    dlg = clean_dialog(source)
    if (dlg.meta.get(REVIEW_KEY) or {}).get('status') != 'accepted': raise ValueError('Round has not been accepted')
    return dlg2chat(dlg, plain=True)

def accept(
    source,         # reviewed dialog notebook
    reviewer,       # person accepting the round
    output=None,    # compiled JSON path; `<source>.json` when omitted
    install=False,  # also write to the rounds library (`True` for `ROUNDS_DIR`, or a directory)
):
    "Accept a reviewed dialog and write its canonical history."
    if not reviewer.strip(): raise ValueError('reviewer is required')
    dlg = read_dialog(source)
    if not (prompts := _prompts(dlg)): raise ValueError('Round contains no prompt turns')
    history = dlg2chat(Dialog(prompts, name=dlg.name), plain=True)
    if not history or history[0].role != 'user': raise ValueError('Round must start with a user turn')
    meta = dict(dlg.meta.get(REVIEW_KEY) or {})
    tools = sorted({p.name for m in history for p in m.content if isinstance(p, ToolUse)})
    meta.update(status='accepted', reviewer=reviewer, accepted_version=drona_version(), tools=tools)
    dlg.meta[REVIEW_KEY] = meta
    dlg.save(source)
    output = Path(output) if output else Path(source).with_suffix('.json')
    data = {'meta': meta, 'history': _history_dicts(history)}
    output.write_json(data, indent=2)
    if install:
        lib = (ROUNDS_DIR if install is True else Path(install))/f'{dlg.name}.json'
        lib.parent.mkdir(parents=True, exist_ok=True)
        lib.write_json(data, indent=2)
    return output

def _part_dict(part):
    data = {'type': str(getattr(part.type, 'value', part.type))}
    data.update({k:v for k,v in vars(part).items() if v not in (None, False, {}, []) and k != 'raw'})
    return data

def _history_dicts(history):
    return [{'role': m.role, 'content': [_part_dict(p) for p in m.content]} for m in history]

# %% ../nbs/01_rounds.ipynb #7df69513
def bootstrap_prompt(source):
    "A compact prompt containing one accepted worked round."
    history = compiled_history(source)
    rows = ['The following reviewed Drona round demonstrates the tool route to follow.']
    for m in history:
        if m.role == 'user': rows.append(f'User: {m.text}')
        elif m.role == 'assistant':
            for p in m.content:
                if isinstance(p, Text) and p.text: rows.append(f'Assistant: {p.text}')
                elif isinstance(p, ToolUse): rows.append(f'Assistant tool: {p.name}({json.dumps(p.arguments, sort_keys=True)})')
        elif m.role == 'tool':
            for p in m.content:
                if isinstance(p, ToolResult): rows.append(f'Tool result: {p.text}')
    rows.append('Reply with exactly: DRONA_READY')
    return '\n\n'.join(rows)

def start_commands(
    source,   # accepted review notebook
    root='.', # Ramabana root
    model=None, # optional model name
):
    "The bootstrap and resume commands for an accepted round."
    prompt = bootstrap_prompt(source)
    cmd = ['ramabana', '--root', root]
    if model: cmd += ['--model', model]
    cmd += [prompt]
    return cmd, ['ramabana', '--root', root, '--resume', 'latest']

def start_round(source, root='.', model=None, launch=False):
    "Prepare or launch Ramabana with an accepted Drona round."
    first, resume = start_commands(source, root, model)
    if not launch: return {'bootstrap': first, 'resume': resume}
    subprocess.run(first, check=True)
    return subprocess.run(resume, check=True).returncode

# %% ../nbs/01_rounds.ipynb #5f8482bd
def _print_commands(commands):
    for name, command in commands.items(): print(f'{name}: {shlex.join(command)}')

@call_parse
def capture_cli(output: str, session: str='latest', history: str=str(RAMABANA_HISTORY), name: str=None):
    "Capture a saved Ramabana session for review."
    print(capture(output, session, history, name))

@call_parse
def accept_cli(source: str, reviewer: str='', output: str=None, install: bool=False):
    "Accept a reviewed round and compile its history."
    print(accept(source, reviewer, output, install))

@call_parse
def start_cli(source: str, root: str='.', model: str=None, launch: bool=False):
    "Prepare or launch Ramabana with an accepted round."
    result = start_round(source, root, model, launch)
    if isinstance(result, dict): _print_commands(result)
