"""Move reviewed dialogs between Ramabana, Claude Code, and Codex.

Docs: https://Karthik777.github.io/drona/sessions.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sessions.ipynb.

# %% auto #0
__all__ = ['HOSTS', 'import_session', 'clean_dialog', 'export_session', 'import_cli', 'export_cli']

# %% ../nbs/02_sessions.ipynb #9ba09521
from pathlib import Path
import json

from aidialog.dialog import Dialog
from aidialog.hist import dlg2chat
from aidialog.ipynb import read_ipynb, write_ipynb
from fastcore.script import call_parse
from llmsurgery import ant, oai
from llmsurgery.sess import path_dlg, sess_dlg

from .rounds import REVIEW_KEY, capture

# %% ../nbs/02_sessions.ipynb #aa0b5b0e
HOSTS = ('ramabana', 'claude', 'codex')

def import_session(
    host,            # `ramabana`, `claude`, or `codex`
    output,          # review notebook path
    session='latest', # session id, prefix, or `latest`
    cwd=None,        # project directory for Claude or newest-session lookup
    history=None,    # Ramabana history path
    codex_home=None, # optional Codex home
    name=None,       # dialog name
):
    "Import one host session as an Aidialog review notebook."
    if host not in HOSTS: raise ValueError(f'host must be one of {HOSTS}')
    if host == 'ramabana':
        kwargs = {} if history is None else {'history': history}
        return capture(output, session=session, name=name, **kwargs)
    if session == 'latest':
        if host == 'claude':
            path = max(ant.sess_dir(cwd).glob('*.jsonl'), key=lambda p:p.stat().st_mtime)
        else: _, path = oai.project_thread(cwd or '.', codex_home or oai.CODEX_HOME)
        dlg = path_dlg('ant' if host == 'claude' else 'oai', path, name=name, mx=None)
    else: dlg = sess_dlg(session, cwd=cwd, codex_home=codex_home, name=name, mx=None)
    source = dict(dlg.meta.get('llmsurgery') or {})
    source['host'] = host
    review = {'status': 'review', 'source': source}
    dlg.meta[REVIEW_KEY] = review
    dlg.mk_message('# Drona review\n\nEdit this dialog in Leela before exporting it.', idx=0,
                   msg_type='note', skipped=1, meta={REVIEW_KEY: review})
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    write_ipynb(dlg, output)
    return output

# %% ../nbs/02_sessions.ipynb #d8739129
def clean_dialog(source):
    "Prompt messages from a Drona notebook, without review notes."
    dlg = read_ipynb(source)
    if not dlg: raise ValueError(f'Could not read dialog {source}')
    prompts = [m for m in dlg if m.msg_type == 'prompt' and not m.skipped]
    if not prompts: raise ValueError('Dialog contains no prompt turns')
    return Dialog(prompts, name=dlg.name, meta=dlg.meta)

def export_session(
    source,          # Drona review notebook
    host,            # `ramabana`, `claude`, or `codex`
    output=None,     # JSON output for Ramabana or Codex
    cwd=None,        # Claude project directory
):
    "Compile one Drona notebook for a target host."
    if host not in HOSTS: raise ValueError(f'host must be one of {HOSTS}')
    dlg = clean_dialog(source)
    if host == 'claude': return ant.dlg2sess(dlg, cwd=cwd)
    if host == 'codex':
        items = list(oai.dlg2items(dlg))
        if output: Path(output).write_text(json.dumps(items, indent=2))
        return items
    from drona.rounds import bootstrap_prompt
    prompt = bootstrap_prompt(source)
    if output: Path(output).write_text(prompt)
    return prompt

# %% ../nbs/02_sessions.ipynb #b895cc91
@call_parse
def import_cli(host: str, output: str, session: str='latest', cwd: str=None,
               history: str=None, codex_home: str=None, name: str=None):
    "Import a host session as a review notebook."
    print(import_session(host, output, session, cwd, history, codex_home, name))

@call_parse
def export_cli(source: str, host: str, output: str=None, cwd: str=None):
    "Compile a review notebook for another host."
    result = export_session(source, host, output, cwd)
    if host == 'claude': print(result)
    elif output: print(output)
    else: print(json.dumps(result, indent=2) if host == 'codex' else result)
