"""Measure which tools agents call, how often they fail, and where the shell stands in for a dedicated tool.

Docs: https://Karthik777.github.io/drona/tools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_tools.ipynb.

# %% auto #0
__all__ = ['HISTORIES', 'tool_report', 'fmt_report', 'tools_cli']

# %% ../nbs/03_tools.ipynb #ba1f72ae
from collections import Counter, defaultdict
from datetime import datetime
from json import dumps
import re
from fastcore.xtras import Path
from fastcore.foundation import L
from fastcore.script import call_parse

from .core import read_history, tool_args, bypass_tool

# %% ../nbs/03_tools.ipynb #55021db5
HISTORIES = L(Path.home()/f'.config/{app}/{kind}-history.jsonl' for app in ('ramabana', 'leela') for kind in ('agent', 'inline')).filter(Path.exists)

def _epoch(t):
    "`t` as seconds since the epoch, from a number, numeric string, or ISO date."
    if t in (None, ''): return None
    try: return float(t)
    except ValueError: return datetime.fromisoformat(t).timestamp()

def _detail_key(detail):
    "The first line of `detail` with digits normalised, so repeated failures group together."
    return re.sub(r'\d+', 'N', str(detail or '').partition('\n')[0])[:80]

def tool_report(
    turns,      # history turns from `read_history`
    since=None, # epoch or ISO date lower bound on `at`
    model=None, # restrict to one model name
):
    "Per-tool call and failure counts, shell bypasses, and the same split per model."
    since, calls, fails, details, bypass = _epoch(since), Counter(), Counter(), defaultdict(Counter), Counter()
    models = defaultdict(lambda: dict(calls=0, shell=0, bypass=0))
    for t in turns:
        if (since and (t.get('at') or 0) < since) or (model and t.get('model') != model): continue
        m = models[t.get('model') or '?']
        for a in t.get('activity') or []:
            tool = a.get('tool') or '?'
            calls[tool] += 1; m['calls'] += 1
            if a.get('ok') is False: fails[tool] += 1; details[tool][_detail_key(a.get('detail'))] += 1
            if tool == 'run_shell':
                m['shell'] += 1
                if b := bypass_tool(tool_args(a).get('command')): bypass[b] += 1; m['bypass'] += 1
    tools = {k: dict(calls=v, fails=fails[k], fail_rate=round(fails[k]/v, 3), failures=[[d,n] for d,n in details[k].most_common(3)])
             for k,v in calls.most_common()}
    return dict(calls=sum(calls.values()), tools=tools, bypass=dict(bypass.most_common()), models=dict(models))

def fmt_report(r):
    "`r` as a text table followed by bypass and per-model summary lines."
    w = max(map(len, r['tools']), default=4)
    rows = [f"{'tool':<{w}}  calls  fail%  top failure"]
    rows += [f"{t:<{w}}  {v['calls']:>5}  {100*v['fail_rate']:>4.0f}%  {v['failures'][0][0] if v['failures'] else ''}" for t,v in r['tools'].items()]
    rows.append(f"\n{r['calls']} calls; bypass: " + (', '.join(f'{k}={v}' for k,v in r['bypass'].items()) or 'none'))
    rows += [f"{m}: {v['calls']} calls, {v['shell']} shell, {v['bypass']} bypass" for m,v in r['models'].items()]
    return '\n'.join(rows)


# %% ../nbs/03_tools.ipynb #ce493ed0
@call_parse
def tools_cli(
    history: str='',  # comma-separated history paths (default: every known history)
    since: str='',    # epoch or ISO date lower bound
    model: str='',    # restrict to one model
    json: bool=False, # print the report as JSON
):
    "Report tool usage, failures and shell bypasses across agent histories."
    paths = L(history.split(',')).filter() if history else HISTORIES
    r = tool_report(paths.map(read_history).concat(), since or None, model or None)
    print(dumps(r, indent=2) if json else fmt_report(r))

