"""Assess Ramabana tool routes and build a Urai warm-start history.

Docs: https://Karthik777.github.io/drona/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['RAMABANA_HISTORY', 'SHELL_TOOLS', 'ROUND_REVISION', 'ROUNDS_DIR', 'SEEDS_DIR', 'Finding', 'Assessment',
           'read_history', 'tool_args', 'bypass_tool', 'denial_reason', 'assess_turn', 'assess_history', 'call_valid',
           'as_tools', 'round_calls', 'round_valid', 'load_rounds', 'round_msgs', 'warm_start', 'dhrona_version',
           'receipt_path', 'register_completion', 'completion_valid', 'prepare_chat', 'main']

# %% ../nbs/00_core.ipynb #d04693b6
from dataclasses import dataclass, asdict
import json, re, sys, time, uuid, inspect, functools
from fastcore.basics import ifnone
from fastcore.xtras import Path
from fastcore.script import call_parse
from fastcore.xdg import xdg_state_home, xdg_config_home
from fastcore.foundation import L
from urai import ToolCall, mk_tool_res_msg
import dhrona

# %% ../nbs/00_core.ipynb #2edea58c
@dataclass(frozen=True)
class Finding:
    "One tool-route problem in a recorded turn."
    kind: str
    tool: str
    index: int
    message: str

@dataclass(frozen=True)
class Assessment:
    "The route score and findings for one or more turns."
    score: int
    calls: int
    findings: tuple[Finding, ...]

# %% ../nbs/00_core.ipynb #8e5631ea
RAMABANA_HISTORY = Path.home()/'.config/ramabana/agent-history.jsonl'

def _loads(s):
    try: return json.loads(s)
    except (json.JSONDecodeError, TypeError): return None

def read_history(
    path=RAMABANA_HISTORY, # Ramabana `agent-history.jsonl` path
    session=None,         # optional session id
):
    "Read completed Ramabana turns in append order, skipping partial lines."
    r = L(Path(path).expanduser().readlines()).map(_loads).filter(lambda x: isinstance(x, dict))
    return r if not session else r.filter(lambda x: x.get('session')==session)

def tool_args(action):
    "The call arguments of `action` as a dict."
    a = action.get('args')
    if isinstance(a, str): a = _loads(a)
    return a if isinstance(a, dict) else {}

# %% ../nbs/00_core.ipynb #cf182995
_RESEARCH_TOOLS = {'web_search', 'read_url', 'search_code', 'run_shell'}
_SCHEMA_ERRS = ('could not parse commands', 'JSONDecodeError', 'JSON decoder')
SHELL_TOOLS = (
    (r'git\s+status\b', 'git_status'), (r'git\s+diff\b', 'git_diff'), (r'git\s+(log|show)\b', 'git_log'),
    (r'git\s+commit\b', 'git_commit'), (r'git\s+(checkout|switch)\b', 'git_checkout'), (r'git\s+stash\b', 'git_stash'),
    (r'git\s+(push|pull|fetch)\b', 'git_remote'), (r'(rg|grep|ag)\b', 'grep'), (r'(find|fd)\b', 'ls'), (r'(ls|tree)\b', 'ls'),
    (r'(sed|perl)\s+-p?i\b', 'replace_text'), (r'(cat\s*>|tee\b)', 'create_file'), (r'sed\s+-n\b|(cat|head|tail|nl)\b', 'view_file'),
    (r'(curl|wget)\b', 'read_url'))
_PREFIX = re.compile(r'^(env(\s+-u\s+\S+|\s+\w+=\S+)*\s+|(\w+=\S+\s+)+)')
_GIT_OPTS = re.compile(r'^git\s+((-[Cc]\s+\S+|--\S+)\s+)+')

def _segments(command):
    for s in re.split(r'&&|;|\|\|', command):
        s = _GIT_OPTS.sub('git ', _PREFIX.sub('', s.strip()))
        if s and not s.startswith('cd '): yield s.split('|')[0].strip()

def bypass_tool(command, offered=None):
    "The dedicated tool `command` stands in for, if any."
    if not command: return None
    if re.search(r'&\s*$', command.strip()) and not command.strip().endswith('&&'): hit = 'run_shell_bg'
    else: hit = next((t for s in _segments(command) for rx,t in SHELL_TOOLS if re.match(rx, s)), None)
    return hit if hit and (offered is None or hit in offered) else None

def _is_fossick_repo(action):
    text = ' '.join(str(v) for v in tool_args(action).values())
    return action.get('tool') == 'run_shell' and 'fossick read-gh-repo' in text

def _first_research_finding(prompt, activities):
    if 'github' not in prompt.lower() or 'fossick' not in prompt.lower(): return None
    research = ((i, action) for i, action in enumerate(activities) if action.get('tool') in _RESEARCH_TOOLS)
    index, action = next(research, (None, None))
    if action is None or _is_fossick_repo(action): return None
    return Finding('route', action.get('tool', ''), index, 'Use fossick read-gh-repo as the first repository research call.')

def _failure_key(action): return (action.get('tool', ''), json.dumps(tool_args(action), sort_keys=True, default=str))

_DENIED = 'Denied by human operator'

def denial_reason(action):
    "The operator's reason if `action` is a refused ask, else `None`."
    if action.get('ok') is not False: return None
    detail = str(action.get('detail') or '')
    if action.get('kind') != 'ask' and not detail.startswith(_DENIED): return None
    return detail.partition('Reason given:')[2].strip() or 'no reason given'

def _failure_findings(index, action, failed):
    if action.get('ok') is not False or denial_reason(action) is not None: return ()
    tool, detail, findings = action.get('tool', ''), str(action.get('detail', '')), []
    key = _failure_key(action)
    if key in failed: findings.append(Finding('repeat_failure', tool, index, 'Diagnose or change route before repeating a failed call.'))
    failed.add(key)
    if any(s in detail for s in _SCHEMA_ERRS):
        findings.append(Finding('schema', tool, index, 'Send arguments that match the tool schema exactly.'))
    if tool == 'run_shell' and ('usage:' in detail or 'unrecognized arguments' in detail):
        findings.append(Finding('tool_protocol', tool, index, 'Read the project command contract before retrying.'))
    return tuple(findings)

def _denial_finding(index, action, denied):
    key, retry = _failure_key(action), None
    if key in denied: retry = Finding('denial_retry', action.get('tool', ''), index, 'Ask the user about the refused call instead of retrying it.')
    if denial_reason(action) is not None: denied.add(key)
    return retry

def assess_turn(turn, denied=()):
    "Assess the tool route recorded in one Ramabana turn; `denied` holds calls refused in the previous turn."
    activities, findings, failed, bypassed, denied = turn.get('activity') or [], [], set(), set(), set(denied)
    route_finding = _first_research_finding(turn.get('prompt', ''), activities)
    if route_finding: findings.append(route_finding)
    for ind, a in enumerate(activities):
        if a.get('tool') == 'run_shell' and (t := bypass_tool(str(tool_args(a).get('command', '')))) and t not in bypassed:
            bypassed.add(t); findings.append(Finding('bypass', 'run_shell', ind, f'Use {t} instead of run_shell for this.'))
        if retry := _denial_finding(ind, a, denied): findings.append(retry)
        findings.extend(_failure_findings(ind, a, failed))
    return Assessment(max(0, 100 - 20*len(findings)), len(activities), tuple(findings))

def _carried(prev, turn):
    "Calls refused in `prev` that `turn` may still be retrying: same session, and no question asked in between."
    if prev is None or prev.get('session') != turn.get('session') or '?' in str(prev.get('reply') or ''): return set()
    return {_failure_key(a) for a in prev.get('activity') or [] if denial_reason(a) is not None}

def assess_history(turns):
    "Assess several turns as one route corpus, carrying refusals into the next turn of the same session."
    turns = list(turns)
    assessments = [assess_turn(t, _carried(p, t)) for p,t in zip([None]+turns, turns)]
    findings = tuple(f for a in assessments for f in a.findings)
    return Assessment(max(0, 100 - 20*len(findings)), sum(a.calls for a in assessments), findings)

# %% ../nbs/00_core.ipynb #2d9bf58b
ROUND_REVISION = 1
ROUNDS_DIR = xdg_config_home()/'dhrona/rounds'
SEEDS_DIR = Path(dhrona.__file__).parent/'seeds'

def call_valid(args, fn):
    "Would `fn` accept `args` as keyword arguments?"
    try: inspect.signature(fn).bind(**args); return True
    except (TypeError, ValueError): return False

def _tool_name(f):
    if isinstance(f, str): return f
    if isinstance(f, functools.partial): return _tool_name(f.func)
    if callable(f): return getattr(f, '__name__', type(f).__name__)
    raise TypeError('tools must be tool callables, names, or a name→callable dict')

def as_tools(tools):
    "Tools keyed by name, from a dict or an iterable of callables, partials, or names (a name maps to `None`)."
    return dict(tools) if isinstance(tools, dict) else {_tool_name(f): None if isinstance(f, str) else f for f in tools}

def round_calls(rnd):
    "The `(tool, arguments)` pairs an accepted round makes."
    return [(p['name'], p.get('arguments') or {}) for m in rnd['history'] for p in m['content'] if p['type']=='tool_use']

def round_valid(rnd, tools):
    "Do all of `rnd`'s calls bind to `tools`? A `None` tool checks the name only."
    return all(n in tools and (tools[n] is None or call_valid(a, tools[n])) for n,a in round_calls(rnd))

def load_rounds(dirs=None):
    "Accepted rounds from the library and packaged seeds, skipping unreadable files."
    rs = [_loads(p.read_text()) for d in ifnone(dirs, [ROUNDS_DIR, SEEDS_DIR]) for p in sorted(Path(d).glob('*.json'))]
    return [r for r in rs if isinstance(r, dict) and r.get('meta', {}).get('status')=='accepted']

def _tc(p): return ToolCall(p['name'], p.get('arguments') or {}, **({'id': p['id']} if p.get('id') else {}))

def round_msgs(rnd):
    "Canonical Urai messages from an accepted round."
    res, tcs = [], {}
    for m in rnd['history']:
        parts = m['content']
        if m['role']=='tool':
            res += [mk_tool_res_msg(tcs.get(p.get('id')) or _tc(p), p.get('text', '')) for p in parts if p['type']=='tool_result']
            continue
        msg = {'role': m['role'], 'content': '\n'.join(p['text'] for p in parts if p['type']=='text' and p.get('text'))}
        if calls := [_tc(p) for p in parts if p['type']=='tool_use']:
            tcs.update({tc['id']: tc for tc in calls}); msg['tool_calls'] = calls
        res.append(msg)
    return res

def warm_start(tools=None, model=None, limit=2, dirs=None):
    "Canonical Urai history from accepted rounds that fit the offered tools, best-ranked and same-model first."
    rs = load_rounds(dirs)
    if tools is not None:
        tools = as_tools(tools)
        rs = [r for r in rs if round_valid(r, tools)]
    rs = sorted(rs, key=lambda r: (r['meta'].get('rank', 50), r['meta'].get('model') != model))[:limit]
    return [m for r in rs for m in round_msgs(r)]

def dhrona_version():
    "The warm-start revision."
    return f'{dhrona.__version__}:{ROUND_REVISION}'

def receipt_path(state=None):
    "The completion receipt file."
    return Path(state) if state else xdg_state_home()/'dhrona/completions.json'

def register_completion(state=None):
    "Record one clean round and return its completion id."
    path, cid = receipt_path(state), uuid.uuid4().hex
    records = path.read_json() if path.exists() else {}
    records[cid] = {'version': dhrona_version(), 'at': time.time()}
    path.write_json(records, indent=2)
    return cid

def completion_valid(cid, state=None):
    "Does `cid` name a completion for the current round?"
    path = receipt_path(state)
    if not cid or not path.exists(): return False
    return (path.read_json().get(cid) or {}).get('version') == dhrona_version()

def prepare_chat(chat, tools=None, model=None):
    "Prepend the Dhrona warm start to an empty Urai-compatible chat."
    if chat.hist: raise ValueError('Dhrona prepares an empty chat only')
    chat.hist = chat.fmt2hist(warm_start(tools, model))
    if hasattr(chat, '_recreate_conv'): chat._recreate_conv()
    return chat

# %% ../nbs/00_core.ipynb #f4e8294d
@call_parse
def main(
    history: str=str(RAMABANA_HISTORY), # Ramabana history path
    session: str=None,                  # optional session id
):
    "Assess persisted Ramabana tool routes."
    if not Path(history).expanduser().exists(): sys.exit(f'No history at {history}')
    a = assess_history(read_history(history, session))
    print(json.dumps({'score': a.score, 'calls': a.calls, 'findings': [asdict(f) for f in a.findings]}, indent=2))
